FROM node:alpine

ENV DOKCER="https://github.com/SaintWe/Sub-Store-Docker.git" \
    TZ=Asia/Shanghai

RUN apk update && \
    apk add --no-cache --virtual .build-deps \
    ca-certificates \
    curl \
    tzdata \
    git \
    nodejs \
    npm \
    nginx\
    gettext\
    && rm -fr /var/cache/apk/* \
    && npm install -g cnpm pnpm \
    && mkdir /Sub-Store \
    && git clone https://github.com/sub-store-org/Sub-Store-Front-End.git /Sub-Store/frontend \
    && cd /Sub-Store/frontend \
    && pnpm install \
    && pnpm run build \
    && mkdir /git \
    && git clone ${DOKCER} /git/Docker \
    && mkdir -p /etc/nginx/conf.d \
    && cp -r /git/Docker/nginx/frontend* /etc/nginx/conf.d/ \
    && cp -r /git/Docker/nginx/nginx.conf /etc/nginx/ \
    && chmod +x /git/Docker/frontend/frontend.sh

WORKDIR /Sub-Store

ENTRYPOINT ["/git/Docker/frontend/frontend.sh"]
