FROM node:alpine

ENV DOKCER="https://github.com/SaintWe/Sub-Store-Docker.git" \
    TZ=Asia/Shanghai

RUN apk add --no-cache ca-certificates \
    tzdata \
    git \
    nginx \
    gettext \
    && rm -fr /var/cache/apk/* \
    && npm install -g cnpm pm2 pnpm \
    && git clone https://github.com/sub-store-org/Sub-Store.git /Sub-Store \
    && cd /Sub-Store/backend \
    && pnpm install \
    && mkdir /git \
    && git clone ${DOKCER} /git/Docker \
    && mkdir -p /etc/nginx/conf.d \
    && cp -r /git/Docker/nginx/backend* /etc/nginx/conf.d/ \
    && cp -r /git/Docker/nginx/nginx.conf /etc/nginx/ \
    && chmod +x /git/Docker/backend/backend.sh \
    && apk del git tzdata

WORKDIR /Sub-Store

ENTRYPOINT ["/git/Docker/backend/backend.sh"]
