FROM node:alpine

RUN apk add --no-cache tzdata git nginx curl && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    rm -fr /var/cache/apk/* && \
    npm install -g pm2 pnpm && \
    git clone https://github.com/sub-store-org/Sub-Store.git /Sub-Store && \
    cd /Sub-Store/backend && \
    pnpm install && \
    mkdir /git && \
    git clone https://github.com/SaintWe/Sub-Store-Docker.git /git/Docker && \
    mkdir -p /etc/nginx/conf.d && \
    cp -r /git/Docker/nginx/backend.conf /etc/nginx/conf.d/ && \
    cp -r /git/Docker/nginx/nginx.conf /etc/nginx/ && \
    chmod +x /git/Docker/backend/backend.sh && \
    apk del git tzdata

WORKDIR /Sub-Store

ENTRYPOINT ["/git/Docker/backend/backend.sh"]
