name: 构建 Sub-Store 前端

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 2 */3 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install and Build
        run: |
          pnpm install
          pnpm run build

      - name: Update dist folder to repository
        env:
          DIST_REPO: ${{ env.GITHUB_REPOSITORY }}
          GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS_TOKEN }}
        run: |
          git config --global user.email "Action@GitHub.com"
          git config --global user.name "GitHub Action"
          cd dist && git init && git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://$GITHUB_TOKEN@github.com/$DIST_REPO.git" dist:dist
