name: 构建 Sub-Store

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'dist/**'
  schedule:
    - cron: "0 2 */3 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v2

      # docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 设置 docker 环境
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # build 并且 push docker 镜像
      - name: Build and push
        id: docker_build_backend
        uses: docker/build-push-action@v3
        with:
          network: host
          platforms: linux/amd64,linux/arm64
          context: ./
          file: ./backend/DockerFile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sub-store-backend:latest

      # 打印 docker 镜像 SHA256 Hash 值
      - name: Image digest
        run: echo ${{ steps.docker_build_backend.outputs.digest }}

      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install and Build
        run: |
          cd ..
          git clone https://github.com/sub-store-org/Sub-Store-Front-End.git
          cd Sub-Store-Front-End
          npm install -g pnpm
          pnpm install
          pnpm run build
          rm -rf "$GITHUB_WORKSPACE/dist"
          cp -r ./dist "$GITHUB_WORKSPACE/"

      - name: Update dist folder to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS_TOKEN }}
        run: |
          git config --global user.email "Action@GitHub.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" main:main
